const AUMENTAR_COUNT = 'AUMENTAR_COUNT';
const CAMBIAR_INSTRUCTOR = 'CAMBIAR_INSTRUCTOR';
const  MODIFICAR_ALUMNOS = 'MODIFICA_ALUMNOS';

module.exports = {
    AUMENTAR_COUNT,
    CAMBIAR_INSTRUCTOR,
    MODIFICAR_ALUMNOS
}